spring.datasource.username=postgres
spring.datasource.url=${SUPABASE_URL}
spring.datasource.password=${SUPABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver